version: "3.7"

services:
    database_ignite:
        image: postgres
        container_name: database_ton
        restart: always
        ports:
            - 5440:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=2022ton
            - POSTGRES_DB=ton
        volumes:
            - pgdata:/data/postgres
    # app:
    #     build: .
    #     container_name: ton
    #     ports: 
    #         - 3333:3333
    #     volumes:
    #         - .:/usr/app
    #     links:
    #         - database_ton
    #     depends_on:
    #         - database_ton

volumes:
    pgdata: 
        driver: local